### ISSUE TITLE
Transcripts werken niet meer in ValkyriaBot 8

### ISSUE THREAD

**Issue by d6system** [Got-IT-Systems/Serveerster#15]

**Comment by d6system** [comment]
Uitleg: /transcript geeft geen respons. Ook sluiten van tickets eindigt niet met een transcript.

**Comment by d6system** [comment]
```TypeError: Cannot read properties of undefined (reading 'avatarURL')
    at Object.code (/home/amp/.ampdata/instances/ServeersterTest01/node-server/app/blocks/get_user_info_x3.js:175:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BlockUtils.executeBlock (/home/amp/.ampdata/instances/ServeersterTest01/node-server/app/bot.js:1:424693)
    at async BlockUtils.runNextBlock2 (/home/amp/.ampdata/instances/ServeersterTest01/node-server/app/bot.js:1:426449)
[12/12/2024, 9:07:25 PM] DBB INFO: Join our Discord server (https://discord.gg/PAzxTDw), read our DBB Documentation (https://dbb.software/) or check out our Steam Community if you need help!
[12/12/2024, 9:07:25 PM] DBB WARN: 
┌────────────────────────────────────────────────────┐
│                                                    │
│   ERROR:                                           │
│                                                    │
│   Workspace: Transcript Tickets [ID: NG6CPJNG5k]   │
│   Block: get_user_info_x3 [#13]                    │
│                                                    │
│   ↓ The error will be displayed below ↓            │
│                                                    │
└────────────────────────────────────────────────────┘
TypeError: Cannot read properties of undefined (reading 'avatarURL')
    at Object.code (/home/amp/.ampdata/instances/ServeersterTest01/node-server/app/blocks/get_user_info_x3.js:175:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BlockUtils.executeBlock (/home/amp/.ampdata/instances/ServeersterTest01/node-server/app/bot.js:1:424693)
    at async BlockUtils.runNextBlock2 (/home/amp/.ampdata/instances/ServeersterTest01/node-server/app/bot.js:1:426449)
[12/12/2024, 9:07:25 PM] DBB INFO: Join our Discord server (https://discord.gg/PAzxTDw), read our DBB Documentation (https://dbb.software/) or check out our Steam Community if you need help!```

**Comment by d6system** [comment]
Moet worden vervangen door 1x Get User Info ipv 3x
